name: SandBox
version: '1.0-SNAPSHOT'
main: fr.lvxn.sandBox.SandBox
api-version: '1.20'
author: Lvxn456
commands:
  br:
    description: commande de test
    permission: br.use
  bc:
    description: commande de broadcast
    permission: bc.use
  timerestart:
    description: broadcast restart timer
    permission: restart.use